# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='board',
        ),
        migrations.AddField(
            model_name='webhook',
            name='board',
            field=models.ManyToManyField(to='core.Board'),
        ),
    ]
